import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";

import { validateAgentTask } from "../scripts/agent-task.js";
import { validateAgentRolePolicy } from "../scripts/agent-role-policy.js";
import { openAgentTaskRegistry, registerAgentTask, transitionAgentTask } from "../scripts/agent-task-registry.js";
import { acquireAgentWorkerLease } from "../scripts/agent-worker-lease.js";
import {
  validateAgentDocumentationPolicy,
  validateAgentDocumentationInput,
  validateAgentDocumentationProposal,
  documentationPathRequiresHumanReview,
  proposeAgentDocumentation,
  applyAgentDocumentation,
  main,
} from "../scripts/agent-documentation.js";

const T0="2026-09-17T15:00:00Z",T1="2026-09-17T15:01:00Z";
/** @param {string} value */
function digest(value){return crypto.createHash("sha256").update(value).digest("hex");}
/** @param {string} cwd @param {string[]} args */
function git(cwd,args){const result=spawnSync("git",args,{cwd,encoding:"utf8"});if(result.status!==0)throw new Error("fixture git failed");return result.stdout.trim();}
/** @param {boolean} [withGovernance] */
function repoFixture(withGovernance=true){const root=fs.mkdtempSync(path.join(os.tmpdir(),"agent-docs-")),repo=path.join(root,"repo"),worktree=path.join(root,"worktree");fs.mkdirSync(repo);git(repo,["init","-q"]);git(repo,["config","user.email","test@example.invalid"]);git(repo,["config","user.name","Test User"]);fs.mkdirSync(path.join(repo,"docs"));fs.writeFileSync(path.join(repo,"README.md"),"# Demo\n\nOld command.\n");fs.writeFileSync(path.join(repo,"docs","architecture.md"),"# Architecture\n\nOld path.\n");if(withGovernance)fs.writeFileSync(path.join(repo,"AGENTS.md"),"# Agent instructions\n\nDo not change automatically.\n");fs.writeFileSync(path.join(repo,"package.json"),"{\"name\":\"fixture\",\"private\":true}\n");git(repo,["add","."]);git(repo,["commit","-qm","initial"]);const commit=git(repo,["rev-parse","HEAD"]);git(repo,["worktree","add","-q","-b","docs-test",worktree,commit]);return{root,repo,worktree,commit};}
/** @param {string} commit @param {"LOW"|"MEDIUM"} [risk] @returns {any} */
function rawTask(commit,risk="LOW"){return{version:1,id:"task:docs",role:"docs",repository:{id:"demo",baseCommit:commit},createdAt:T0,risk,objective:"Correct evidence-backed documentation drift",authority:{filesystem:"WORKTREE_WRITE",shell:"NONE",network:"NONE",merge:false,deploy:false,productionMutation:false},scope:{allowedPaths:["README.md","docs/**","AGENTS.md"],deniedPaths:[],requiredChecks:["documentation-drift","lint"]},dependsOn:["task:docs-audit"]};}
/** @returns {any} */
function rawRoles(){return{version:1,roles:[{id:"docs",maxRisk:"MEDIUM",authority:{filesystem:"WORKTREE_WRITE",shell:"BOUNDED",network:"NONE"},writeMode:"LEASED_WORKTREE"}]};}
/** @param {"PROPOSE_ONLY"|"ALLOW_LOW_RISK_WORKTREE"} [mode] @returns {any} */
function rawPolicy(mode="PROPOSE_ONLY"){return{version:1,repository:"demo",allowedPathPatterns:["README.md","docs/**","AGENTS.md"],humanReviewPathPatterns:["docs/governance/**"],applyMode:mode,maxFiles:3,maxFileBytes:65536,maxTotalBytes:131072,requiredChecks:["documentation-drift","lint"]};}
/** @param {string} commit @param {string} filePath @param {string} content @returns {any} */
function rawInput(commit,filePath,content){return{version:1,taskId:"task:docs",repository:{id:"demo",commit},sourceTaskIds:["task:docs-audit"],evidence:[{id:"doc-drift",source:"documentation-drift",status:"FAIL",summary:"Documentation contains a stale command or path",path:filePath}],contextFiles:[{path:filePath,sha256:digest(content),content}],unknowns:[]};}
/** @param {string} filePath @param {string} before @param {string} content @returns {any} */
function rawProposal(filePath,before,content){return{version:1,taskId:"task:docs",evidenceIds:["doc-drift"],rationale:"Update only the evidence-backed documentation reference",files:[{path:filePath,operation:"MODIFY",beforeSha256:before,content}]};}
/** @param {string} commit @param {"LOW"|"MEDIUM"} [risk] */
function taskValue(commit,risk="LOW"){const result=validateAgentTask(rawTask(commit,risk));assert.equal(result.valid,true,JSON.stringify(result.errors));if(!result.valid||!result.task)throw new Error("bad task fixture");return result.task;}
function roleValue(){const result=validateAgentRolePolicy(rawRoles());assert.equal(result.valid,true,JSON.stringify(result.errors));if(!result.valid||!result.policy)throw new Error("bad role fixture");return result.policy;}
/** @param {"PROPOSE_ONLY"|"ALLOW_LOW_RISK_WORKTREE"} [mode] */
function policyValue(mode="PROPOSE_ONLY"){const result=validateAgentDocumentationPolicy(rawPolicy(mode));assert.equal(result.valid,true,JSON.stringify(result.errors));if(!result.valid||!result.policy)throw new Error("bad policy fixture");return result.policy;}
/** @param {string} commit @param {string} filePath @param {string} content */
function inputValue(commit,filePath,content){const result=validateAgentDocumentationInput(rawInput(commit,filePath,content));assert.equal(result.valid,true,JSON.stringify(result.errors));if(!result.valid||!result.input)throw new Error("bad input fixture");return result.input;}
/** @param {any} request @param {string} content */
function modelResponse(request,content){return{version:1,backend:request.backend,model:request.model,content,finishReason:"stop",usage:{inputTokens:100,outputTokens:100},semantics:"synthetic normalized response"};}
/** @param {string} dbFile @param {any} task */
function runningLease(dbFile,task){const db=openAgentTaskRegistry(dbFile);registerAgentTask(db,task,T0);transitionAgentTask(db,{taskId:task.id,fromState:"QUEUED",toState:"ROUTED",expectedRevision:0,at:"2026-09-17T15:00:10Z"});const acquired=acquireAgentWorkerLease(db,{taskId:task.id,workerId:"worker-docs",at:"2026-09-17T15:00:20Z",ttlSeconds:600});transitionAgentTask(db,{taskId:task.id,fromState:"ROUTED",toState:"RUNNING",expectedRevision:1,at:"2026-09-17T15:00:30Z"});return{db,leaseId:acquired.lease.leaseId};}

test("documentation policy defaults to proposal-only and requires explicit human-review patterns",()=>{const result=validateAgentDocumentationPolicy(rawPolicy());assert.equal(result.valid,true,JSON.stringify(result.errors));assert.equal(result.policy?.applyMode,"PROPOSE_ONLY");const missing=rawPolicy();missing.humanReviewPathPatterns=[];assert.equal(validateAgentDocumentationPolicy(missing).valid,false);});

test("hard governance paths always require human review",()=>{for(const file of ["AGENTS.md","nested/AGENTS.md",".github/pull_request_template.md","docs/policies/release.md","docs/security-policy.md","SECURITY.md","CODEOWNERS"])assert.equal(documentationPathRequiresHumanReview(file),true,file);for(const file of ["README.md","docs/architecture.md","docs/releases/v2.md"])assert.equal(documentationPathRequiresHumanReview(file),false,file);});

test("ordinary documentation proposal is eligible while AGENTS stays human-review-only",()=>{const readme="# Demo\n\nOld command.\n",task=taskValue("a".repeat(40)),policy=policyValue(),input=inputValue("a".repeat(40),"README.md",readme);let result=validateAgentDocumentationProposal(rawProposal("README.md",digest(readme),"# Demo\n\nNew command.\n"),task,policy,input);assert.equal(result.valid,true,JSON.stringify(result.errors));assert.equal(result.proposal?.status,"PROPOSAL_READY");const agents="# Agent instructions\n\nOld.\n",agentInput=inputValue("a".repeat(40),"AGENTS.md",agents);result=validateAgentDocumentationProposal(rawProposal("AGENTS.md",digest(agents),"# Agent instructions\n\nNew.\n"),task,policy,agentInput);assert.equal(result.valid,true,JSON.stringify(result.errors));assert.equal(result.proposal?.status,"HUMAN_REVIEW_REQUIRED");assert.equal(result.proposal?.files.at(0)?.humanReviewRequired,true);});
test("non-document extension is rejected even when path policy is broad",()=>{const content="export const value = 1;\n",task=taskValue("a".repeat(40));task.scope.allowedPaths=["src/**"];const policy=policyValue();policy.allowedPathPatterns=["src/**"];const input=inputValue("a".repeat(40),"src/value.js",content),proposal=rawProposal("src/value.js",digest(content),"export const value = 2;\n");assert.equal(validateAgentDocumentationProposal(proposal,task,policy,input).valid,false);});

test("proposal generation keeps ordinary docs unchanged on disk and reports apply eligibility only when allowed",async()=>{const fixture=repoFixture(),file="README.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,file,before),proposal=rawProposal(file,digest(before),"# Demo\n\nCurrent command.\n"),invoke=async(/** @type {any} */_config,/** @type {any} */request)=>modelResponse(request,JSON.stringify(proposal));try{let result=await proposeAgentDocumentation(task,roleValue(),policyValue(),input,fixture.worktree,{},"local","docs",{invoke});assert.equal(result.status,"PROPOSAL_READY");assert.equal(result.worktreeApplyPolicyEligible,false);assert.equal(fs.readFileSync(path.join(fixture.worktree,file),"utf8"),before);result=await proposeAgentDocumentation(task,roleValue(),policyValue("ALLOW_LOW_RISK_WORKTREE"),input,fixture.worktree,{},"local","docs",{invoke});assert.equal(result.worktreeApplyPolicyEligible,true);assert.equal(result.worktreeMutationPerformed,false);}finally{fs.rmSync(fixture.root,{recursive:true,force:true});}});

test("hard-protected AGENTS proposal remains human review even when apply policy is enabled",async()=>{const fixture=repoFixture(),file="AGENTS.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,file,before),proposal=rawProposal(file,digest(before),"# Agent instructions\n\nProposed change.\n"),invoke=async(/** @type {any} */_config,/** @type {any} */request)=>modelResponse(request,JSON.stringify(proposal));try{const result=await proposeAgentDocumentation(task,roleValue(),policyValue("ALLOW_LOW_RISK_WORKTREE"),input,fixture.worktree,{},"local","docs",{invoke});assert.equal(result.status,"HUMAN_REVIEW_REQUIRED");assert.equal(result.worktreeApplyPolicyEligible,false);assert.equal(fs.readFileSync(path.join(fixture.worktree,file),"utf8"),before);}finally{fs.rmSync(fixture.root,{recursive:true,force:true});}});
test("safe LOW-risk documentation apply changes only declared doc under active lease",()=>{const fixture=repoFixture(),file="README.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,file,before),state=runningLease(path.join(fixture.root,"control.sqlite"),task),proposal=rawProposal(file,digest(before),"# Demo\n\nCurrent command.\n");try{const result=applyAgentDocumentation(task,roleValue(),policyValue("ALLOW_LOW_RISK_WORKTREE"),input,proposal,state.db,state.leaseId,"worker-docs",T1,fixture.worktree);assert.equal(result.status,"DOCUMENTATION_APPLIED_IN_WORKTREE");assert.equal(result.humanReviewRequired,false);assert.equal(result.checksExecuted,false);assert.equal(result.mergeAuthorized,false);assert.equal(fs.readFileSync(path.join(fixture.worktree,file),"utf8"),"# Demo\n\nCurrent command.\n");assert.deepEqual(result.requiredChecks,["documentation-drift","lint"]);}finally{state.db.close();fs.rmSync(fixture.root,{recursive:true,force:true});}});

test("AGENTS and governance documentation can never enter auto-apply path",()=>{const fixture=repoFixture(),file="AGENTS.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,file,before),state=runningLease(path.join(fixture.root,"control.sqlite"),task),proposal=rawProposal(file,digest(before),"# Agent instructions\n\nProposed change.\n");try{assert.throws(()=>applyAgentDocumentation(task,roleValue(),policyValue("ALLOW_LOW_RISK_WORKTREE"),input,proposal,state.db,state.leaseId,"worker-docs",T1,fixture.worktree),/human-review-required/);assert.equal(fs.readFileSync(path.join(fixture.worktree,file),"utf8"),before);}finally{state.db.close();fs.rmSync(fixture.root,{recursive:true,force:true});}});

test("documentation apply remains LOW-risk-only and lease-owner-bound",()=>{const fixture=repoFixture(),file="README.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),medium=taskValue(fixture.commit,"MEDIUM"),mediumInput=inputValue(fixture.commit,file,before),mediumState=runningLease(path.join(fixture.root,"medium.sqlite"),medium),proposal=rawProposal(file,digest(before),"# Demo\n\nCurrent command.\n");try{assert.throws(()=>applyAgentDocumentation(medium,roleValue(),policyValue("ALLOW_LOW_RISK_WORKTREE"),mediumInput,proposal,mediumState.db,mediumState.leaseId,"worker-docs",T1,fixture.worktree),/limited to LOW risk/);}finally{mediumState.db.close();}const low=taskValue(fixture.commit),lowState=runningLease(path.join(fixture.root,"low.sqlite"),low);try{assert.throws(()=>applyAgentDocumentation(low,roleValue(),policyValue("ALLOW_LOW_RISK_WORKTREE"),inputValue(fixture.commit,file,before),proposal,lowState.db,lowState.leaseId,"other-worker",T1,fixture.worktree),/WRITE lease/);assert.equal(fs.readFileSync(path.join(fixture.worktree,file),"utf8"),before);}finally{lowState.db.close();fs.rmSync(fixture.root,{recursive:true,force:true});}});
test("safe documentation CREATE is allowed only for a new document path",()=>{const fixture=repoFixture(),before=fs.readFileSync(path.join(fixture.worktree,"README.md"),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,"README.md",before),state=runningLease(path.join(fixture.root,"control.sqlite"),task),proposal=/** @type {any} */({version:1,taskId:task.id,evidenceIds:["doc-drift"],rationale:"Add release note",files:[{path:"docs/release-note.md",operation:"CREATE",beforeSha256:null,content:"# Release note\n\nEvidence-backed update.\n"}]});try{const result=applyAgentDocumentation(task,roleValue(),policyValue("ALLOW_LOW_RISK_WORKTREE"),input,proposal,state.db,state.leaseId,"worker-docs",T1,fixture.worktree);assert.equal(result.files.at(0)?.operation,"CREATE");assert.equal(fs.readFileSync(path.join(fixture.worktree,"docs","release-note.md"),"utf8"),"# Release note\n\nEvidence-backed update.\n");}finally{state.db.close();fs.rmSync(fixture.root,{recursive:true,force:true});}});

test("documentation task dependency and required checks are enforced before model",async()=>{const fixture=repoFixture(),file="README.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,file,before);let invoked=false;const invoke=async()=>{invoked=true;throw new Error("unexpected model call");};try{input.sourceTaskIds=["task:missing"];await assert.rejects(()=>proposeAgentDocumentation(task,roleValue(),policyValue(),input,fixture.worktree,{},"local","docs",{invoke}),/sourceTaskIds/);assert.equal(invoked,false);const taskMissing=taskValue(fixture.commit);taskMissing.scope.requiredChecks=["documentation-drift"];await assert.rejects(()=>proposeAgentDocumentation(taskMissing,roleValue(),policyValue(),inputValue(fixture.commit,file,before),fixture.worktree,{},"local","docs",{invoke}),/policy-required check/);assert.equal(invoked,false);}finally{fs.rmSync(fixture.root,{recursive:true,force:true});}});

test("Documentation v1 rejects shell or network authority before model invocation",async()=>{const fixture=repoFixture(),file="README.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,file,before);task.authority.shell="BOUNDED";let invoked=false;const invoke=async()=>{invoked=true;throw new Error("unexpected model call");};try{await assert.rejects(()=>proposeAgentDocumentation(task,roleValue(),policyValue(),input,fixture.worktree,{},"local","docs",{invoke}),/shell NONE and network NONE/);assert.equal(invoked,false);}finally{fs.rmSync(fixture.root,{recursive:true,force:true});}});
test("documentation context mismatch blocks model before proposal generation",async()=>{const fixture=repoFixture(),file="README.md",before=fs.readFileSync(path.join(fixture.worktree,file),"utf8"),task=taskValue(fixture.commit),input=inputValue(fixture.commit,file,before);input.contextFiles[0].content="# Tampered\n";input.contextFiles[0].sha256=digest(input.contextFiles[0].content);let invoked=false;const invoke=async()=>{invoked=true;throw new Error("unexpected model call");};try{await assert.rejects(()=>proposeAgentDocumentation(task,roleValue(),policyValue(),input,fixture.worktree,{},"local","docs",{invoke}),/does not match exact supplied/);assert.equal(invoked,false);}finally{fs.rmSync(fixture.root,{recursive:true,force:true});}});

test("documentation source has no direct subprocess network deployment or provider surface",()=>{const source=fs.readFileSync(new URL("../scripts/agent-documentation.js",import.meta.url),"utf8");assert.doesNotMatch(source,/node:child_process|spawnSync|execFile|execSync|\bfetch\s*\(|https?:\/\/|\bssh\b|\bdocker\b|\bkubectl\b|\bgh\b|process\.env/);});

test("documentation CLI fails closed on incomplete and unknown commands",async()=>{assert.equal(await main(["propose"]),1);assert.equal(await main(["apply"]),1);assert.equal(await main(["unknown"]),1);});
