import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { analyzeChangedSurface, globToRegExp, main, validateChangedSurfacePolicy } from "../scripts/analyze-changed-surface.js";

/** @returns {any} */
function policyRaw(){return{version:1,surfaceRules:[{surface:"frontend",paths:["src/ui/**"]},{surface:"database",paths:["supabase/migrations/**"]},{surface:"api",paths:["src/api/**"]},{surface:"deployment",paths:[".github/workflows/**"]},{surface:"infrastructure",paths:["infra/**"]}],testPaths:["test/**","tests/**"],environmentPaths:[".env.example","config/env/**",".github/workflows/**"],majorDependencies:{mode:"npm-package-json",paths:["package.json"]}};}
/** @param {string} repo @param {string[]} args */
function git(repo,args){return execFileSync("git",args,{cwd:repo,encoding:"utf8"}).trim();}
/** @param {string} repo @param {string} file @param {string} content */
function write(repo,file,content){const target=path.join(repo,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content);}
/** @param {string} repo @param {string} message */
function commit(repo,message){git(repo,["add","."]);git(repo,["commit","-m",message]);return git(repo,["rev-parse","HEAD"]);}
function repo(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"changed-surface-"));git(root,["init","-q"]);git(root,["config","user.email","test@example.com"]);git(root,["config","user.name","Test"]);write(root,"package.json",JSON.stringify({dependencies:{react:"^18.2.0"}}));write(root,"src/ui/app.js","export const app = 1;\n");write(root,"test/app.test.js","test();\n");const base=commit(root,"base");return{root,base};}
function policy(){const r=validateChangedSurfacePolicy(policyRaw());assert.equal(r.valid,true);if(!r.valid||!r.policy)throw new Error("policy fixture invalid");return r.policy;}

test("glob matcher keeps star within a segment and double-star recursive",()=>{assert.equal(globToRegExp("src/*").test("src/a.js"),true);assert.equal(globToRegExp("src/*").test("src/x/a.js"),false);assert.equal(globToRegExp("src/**").test("src/x/a.js"),true);});
test("policy validates explicit surfaces paths and dependency mode",()=>{const r=validateChangedSurfacePolicy(policyRaw());assert.equal(r.valid,true);const duplicate=policyRaw();duplicate.surfaceRules.push({surface:"frontend",paths:["other/**"]});assert.equal(validateChangedSurfacePolicy(duplicate).valid,false);const unsafe=policyRaw();unsafe.testPaths=["../test/**"];assert.equal(validateChangedSurfacePolicy(unsafe).valid,false);});
test("analyzes Git diff into canonical surface flags and metrics",()=>{const {root,base}=repo();write(root,"src/ui/app.js","export const app = 2;\n");write(root,"supabase/migrations/1.sql","select 1;\n");write(root,".env.example","PUBLIC_URL=example\n");write(root,"test/app.test.js","test();\ntest2();\n");write(root,"package.json",JSON.stringify({dependencies:{react:"^19.0.0"}}));const head=commit(root,"head");const evidence=analyzeChangedSurface(root,{baseCommit:base,headCommit:head,collectedAt:"2026-09-16T16:30:00Z",policy:policy()});assert.deepEqual(evidence.surfaces,["database","frontend"]);assert.equal(evidence.flags.testsChanged,true);assert.equal(evidence.flags.environmentChanged,true);assert.equal(evidence.flags.majorDependencyUpgrade,true);assert.equal(evidence.metrics.filesChanged,5);assert.ok(evidence.metrics.additions>0);assert.equal(evidence.evidence.authenticated,false);fs.rmSync(root,{recursive:true,force:true});});
test("non-major dependency changes remain false",()=>{const {root,base}=repo();write(root,"package.json",JSON.stringify({dependencies:{react:"^18.3.0"}}));const head=commit(root,"head");const e=analyzeChangedSurface(root,{baseCommit:base,headCommit:head,collectedAt:"2026-09-16T16:30:00Z",policy:policy()});assert.equal(e.flags.majorDependencyUpgrade,false);fs.rmSync(root,{recursive:true,force:true});});
test("changed unsupported dependency expressions fail closed",()=>{const {root,base}=repo();write(root,"package.json",JSON.stringify({dependencies:{react:"workspace:*"}}));const head=commit(root,"head");assert.throws(()=>analyzeChangedSurface(root,{baseCommit:base,headCommit:head,collectedAt:"2026-09-16T16:30:00Z",policy:policy()}),/unsupported version expression/);fs.rmSync(root,{recursive:true,force:true});});
test("explicit disabled dependency analysis never reads package manifests",()=>{const {root,base}=repo();fs.rmSync(path.join(root,"package.json"));commit(root,"remove package");const head=git(root,["rev-parse","HEAD"]);const raw=policyRaw();raw.majorDependencies={mode:"disabled"};const p=validateChangedSurfacePolicy(raw);assert.equal(p.valid,true);if(!p.valid||!p.policy)return;const e=analyzeChangedSurface(root,{baseCommit:base,headCommit:head,collectedAt:"2026-09-16T16:30:00Z",policy:p.policy});assert.equal(e.flags.majorDependencyUpgrade,false);fs.rmSync(root,{recursive:true,force:true});});
test("full commit ids and explicit timestamps are mandatory",()=>{const {root,base}=repo();write(root,"src/ui/app.js","x\n");const head=commit(root,"head");assert.throws(()=>analyzeChangedSurface(root,{baseCommit:"HEAD",headCommit:head,collectedAt:"2026-09-16T16:30:00Z",policy:policy()}),/full Git object ids/);assert.throws(()=>analyzeChangedSurface(root,{baseCommit:base,headCommit:head,collectedAt:"today",policy:policy()}),/absolute ISO/);fs.rmSync(root,{recursive:true,force:true});});
test("CLI emits canonical evidence without modifying repository",()=>{const {root,base}=repo();write(root,"src/api/users.js","export const x=1;\n");const head=commit(root,"head"),policyFile=path.join(root,"policy.json");fs.writeFileSync(policyFile,JSON.stringify(policyRaw()));const before=git(root,["status","--porcelain"]),original=console.log;let out="";console.log=(...v)=>{out+=`${v.join(" ")}\n`;};try{assert.equal(main(["--root",root,"--base-commit",base,"--head-commit",head,"--collected-at","2026-09-16T16:30:00Z","--policy",policyFile,"--json"]),0);}finally{console.log=original;}assert.deepEqual(JSON.parse(out).surfaces,["api"]);assert.equal(git(root,["status","--porcelain"]),before);fs.rmSync(root,{recursive:true,force:true});});
test("analyzer operational surface is read-only Git plus explicit package files",()=>{const source=fs.readFileSync(new URL("../scripts/analyze-changed-surface.js",import.meta.url),"utf8");assert.match(source,/spawnSync\("git"/);assert.doesNotMatch(source,/\bfetch\s*\(|process\.env|writeFile|rmSync|unlinkSync/);assert.doesNotMatch(source,/git\s+(?:checkout|reset|clean|commit|merge|rebase|push|pull)/);});
