import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { formatTestSelection, main, selectTests, validateTestSelectionPolicy } from "../scripts/select-tests.js";
import { validateChangeSurfaceEvidence } from "../scripts/change-surface-evidence.js";

const BASE="0123456789abcdef0123456789abcdef01234567",HEAD="1123456789abcdef0123456789abcdef01234567";
/** @returns {any} */
function evidenceRaw(){return{version:1,source:{baseCommit:BASE,headCommit:HEAD},metrics:{filesChanged:2,additions:10,deletions:2},surfaces:["frontend"],flags:{testsChanged:false,environmentChanged:false,majorDependencyUpgrade:false},evidence:{source:"local-git-diff",authenticated:false,collectedAt:"2026-09-16T16:40:00Z"}};}
/** @returns {any} */
function policyRaw(){return{version:1,tests:[{id:"typecheck",command:"bun run typecheck",blocking:true},{id:"unit",command:"bun run test",blocking:true},{id:"e2e",command:"bun run test:e2e",blocking:false},{id:"migration",command:"bun run test:migrations",blocking:false},{id:"dependency",command:"bun run test:dependencies",blocking:false}],rules:[{id:"frontend-e2e",surfaces:["frontend"],tests:["e2e"]},{id:"database-migrations",surfaces:["database"],tests:["migration"]},{id:"major-deps",flags:["majorDependencyUpgrade"],tests:["dependency"]},{id:"database-major",surfaces:["database"],flags:["majorDependencyUpgrade"],tests:["migration","dependency"]}]};}
function pair(e=evidenceRaw(),p=policyRaw()){const er=validateChangeSurfaceEvidence(e),pr=validateTestSelectionPolicy(p);assert.equal(er.valid,true);assert.equal(pr.valid,true);if(!er.valid||!er.evidence||!pr.valid||!pr.policy)throw new Error("fixture invalid");return{e:er.evidence,p:pr.policy};}
/** @param {string} prefix @param {any} value */
function temp(prefix,value){const f=path.join(os.tmpdir(),`${prefix}-${process.pid}-${Math.random()}.json`);fs.writeFileSync(f,typeof value==="string"?value:JSON.stringify(value));return f;}

test("blocking tests are always selected even without matching rules",()=>{const raw=evidenceRaw();raw.surfaces=[];const{e,p}=pair(raw);const report=selectTests(e,p);assert.deepEqual(report.selected.filter((/** @type {any} */ x)=>x.blocking).map((/** @type {any} */ x)=>x.id),["typecheck","unit"]);assert.deepEqual(report.selected.find((/** @type {any} */ x)=>x.id==="typecheck")?.reasons,["required-blocking"]);});
test("surface rule adds advisory test without dropping blockers",()=>{const{e,p}=pair();const report=selectTests(e,p);assert.deepEqual(report.selected.map((/** @type {any} */ x)=>x.id),["e2e","typecheck","unit"]);assert.equal(report.summary.blocking,2);});
test("flag only rule selects configured test",()=>{const raw=evidenceRaw();raw.surfaces=[];raw.flags.majorDependencyUpgrade=true;const{e,p}=pair(raw);assert.equal(selectTests(e,p).selected.some((/** @type {any} */ x)=>x.id==="dependency"),true);});
test("surface plus flag rule requires both conditions",()=>{const a=evidenceRaw();a.surfaces=["database"];const pa=pair(a);assert.equal(selectTests(pa.e,pa.p).selected.find((/** @type {any} */ x)=>x.id==="dependency"),undefined);const b=evidenceRaw();b.surfaces=["database"];b.flags.majorDependencyUpgrade=true;const pb=pair(b);const dependency=selectTests(pb.e,pb.p).selected.find((/** @type {any} */ x)=>x.id==="dependency");assert.ok(dependency);assert.deepEqual(dependency.reasons,["rule:database-major","rule:major-deps"]);});
test("policy rejects no blocking test and unknown test references",()=>{const a=policyRaw();for(const item of a.tests)item.blocking=false;assert.equal(validateTestSelectionPolicy(a).valid,false);const b=policyRaw();b.rules[0].tests=["missing"];assert.equal(validateTestSelectionPolicy(b).valid,false);});
test("policy rejects duplicate ids unsupported surfaces flags and multiline commands",()=>{const a=policyRaw();a.tests.push({...a.tests[0]});assert.equal(validateTestSelectionPolicy(a).valid,false);const b=policyRaw();b.rules[0].surfaces=["private-business-rule"];assert.equal(validateTestSelectionPolicy(b).valid,false);const c=policyRaw();c.rules[0].flags=["testsChanged"];assert.equal(validateTestSelectionPolicy(c).valid,false);const d=policyRaw();d.tests[0].command="first\nsecond";assert.equal(validateTestSelectionPolicy(d).valid,false);});
test("rule must have at least one explicit surface or flag",()=>{const p=policyRaw();p.rules[0].surfaces=[];assert.equal(validateTestSelectionPolicy(p).valid,false);});
test("human output distinguishes blocking and advisory selections",()=>{const{e,p}=pair();const text=formatTestSelection(selectTests(e,p));assert.match(text,/BLOCK  typecheck/);assert.match(text,/ADVISORY  e2e/);assert.match(text,/required-blocking/);});
test("CLI emits machine readable plan without executing test commands",()=>{const ef=temp("select-evidence",evidenceRaw()),pf=temp("select-policy",policyRaw()),original=console.log;let out="";console.log=(...v)=>{out+=`${v.join(" ")}\n`;};try{assert.equal(main(["--evidence-file",ef,"--policy",pf,"--json"]),0);}finally{console.log=original;}const parsed=JSON.parse(out);assert.equal(parsed.selected.some((/** @type {any} */ x)=>x.command==="bun run test:e2e"),true);fs.rmSync(ef,{force:true});fs.rmSync(pf,{force:true});});
test("selection core stays offline read only and has no execution surface",()=>{const source=fs.readFileSync(new URL("../scripts/select-tests.js",import.meta.url),"utf8");assert.match(source,/validateChangeSurfaceEvidence/);assert.doesNotMatch(source,/node:child_process|spawnSync|execFile|\bfetch\s*\(|process\.env|writeFile|execSync/);});
